// js/data.js
// Product database

const products = [
    {
        id: 1,
        name: "OKAZU Lovers Set (230ml/12 jars)",
        category: "Chili oil:Okazu",
        type: "Multi Set",
        flavor: "Original",
        price: 135.00,
        oldPrice: 167.88,
        rating: 5,
        reviews: 32,
        image:"https://www.abokichi.com/cdn/shop/products/OKAZUChiliMiso230ml-12_764a3d60-8c4c-4cd9-bda6-ccd24ca47435.png?v=1682455325&width=480",
        description: "Your new cooking BFF! You can add this to virtually everything. Try it on rice, on meat or tofu, in your burger, ramen and pretty much anything."
    },
    {
        id: 2,
        name: "OKAZU - CHILI MISO - Japanese miso chili oil condiment (230ml)",
        category: "Chili oil:Okazu",
        type: "Single Pack",
        flavor: "Spicy",
        price: 13.99,
        oldPrice: null,
        rating: 4.5,
        reviews: 18,
        image: "https://images-cdn.ubuy.co.in/6356d489ae885319a93ebaf2-okazu-spicy-chili-miso-oil-savoury.jpg",
        description: "Chili Oil is an umami-rich chili, miso, and sesame oil based condiment often eaten with rice in Japan."
    },
    {
        id: 3,
        name: "Instant Miso Soup Tasting Set",
        category: "Miso Soup",
        type: "Multi Set",
        flavor: "Original",
        price: 19.99,
        oldPrice: 24.00,
        rating: 3.8,
        reviews: 12,
        image: "https://www.abokichi.com/cdn/shop/products/20220929_3FlavourMisoSoup2.png?v=1668571649",
        description: "Discover the authentic taste of Japan with our instant miso soup tasting set."
    },
    {
        id: 4,
        name: "ABO Matcha: Uji matcha, Organic, Ceremonial grade",
        category: "Instant Matcha",
        type: "Single Pack",
        flavor: "Original",
        price: 34.00,
        oldPrice: null,
        rating: 5,
        reviews: 24,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShCCAsCZbVc-LPQSbzUfwfS6_YuXjSq-MjMg&s",
        description: "Premium ceremonial grade matcha from Uji, Japan. Perfect for traditional tea ceremonies."
    },
    {
        id: 5,
        name: "OKAZU Original Flavor (230ml)",
        category: "Chili oil:Okazu",
        type: "Single Pack",
        flavor: "Original",
        price: 12.99,
        oldPrice: null,
        rating: 4.7,
        reviews: 28,
        image:"https://www.abokichi.com/cdn/shop/files/13.png?v=1757592587&width=480",
        description: "The original OKAZU flavor that started it all. A perfect blend of umami and spice."
    },
    {
        id: 6,
        name: "Miso Soup Variety Pack (6 Flavors)",
        category: "Miso Soup",
        type: "Multi Set",
        flavor: "Original",
        price: 24.99,
        oldPrice: 29.99,
        rating: 4.5,
        reviews: 16,
        image:"https://bfasset.costco-static.com/U447IH35/as/fvbpsc77v4h8sx9krsht83fv/1716582-894__1?auto=webp&format=jpg&width=350&height=350&fit=bounds&canvas=350,350",
        description: "Experience six different flavors of authentic Japanese miso soup."
    },
    {
        id: 7,
        name: "Matcha Starter Kit",
        category: "Instant Matcha",
        type: "Multi Set",
        flavor: "Original",
        price: 45.00,
        oldPrice: null,
        rating: 4.8,
        reviews: 20,
        image:"https://m.media-amazon.com/images/I/71ZAccbxTdL._AC_UF894,1000_QL80_.jpg",
        description: "Everything you need to start your matcha journey. Includes premium matcha and tools."
    },
    {
        id: 8,
        name: "Coffee Blend - Morning Roast",
        category: "Coffee",
        type: "Single Pack",
        flavor: "Original",
        price: 18.99,
        oldPrice: null,
        rating: 3.8,
        reviews: 14,
        image: "https://thecoffeeco.in/wp-content/uploads/2023/04/Morning-Dew-Medium-Roast-300px.png",
        description: "Start your day right with our specially crafted morning blend coffee."
    },
    {
        id: 9,
        name: "OKAZU Spicy Version (230ml)",
        category: "Chili oil:Okazu",
        type: "Single Pack",
        flavor: "Spicy",
        price: 13.99,
        oldPrice: null,
        rating: 4.9,
        reviews: 35,
        image:"https://m.media-amazon.com/images/I/61du9cQeM+L._AC_UF894,1000_QL80_.jpg",
        description: "For those who love extra heat! Our spiciest version of OKAZU."
    },
    {
        id: 10,
        name: "Premium Miso Soup Set",
        category: "Miso Soup",
        type: "Multi Set",
        flavor: "Original",
        price: 32.00,
        oldPrice: 38.00,
        rating: 5,
        reviews: 22,
        image:"https://cdn.shopify.com/s/files/1/0290/9689/files/Miso_Page_1_480x480.png?v=1679079974",
        description: "Our premium selection of miso soups made with the finest ingredients."
    },
    {
        id: 11,
        name: "Organic Matcha Powder (100g)",
        category: "Instant Matcha",
        type: "Single Pack",
        flavor: "Original",
        price: 28.00,
        oldPrice: null,
        rating: 3.9,
        reviews: 18,
        image: "https://www.abokichi.com/cdn/shop/products/FA8316DD-7979-4823-A6AA-0F100A9E832D.png?v=1675100343",
        description: "100% organic matcha powder sourced directly from Japanese tea farms."
    },
    {
        id: 12,
        name: "Coffee Blend - Dark Roast",
        category: "Coffee",
        type: "Single Pack",
        flavor: "Spicy",
        price: 19.99,
        oldPrice: null,
        rating: 4.4,
        reviews: 11,
        image:"https://i.ebayimg.com/images/g/12YAAOSwm7pmZ3Ts/s-l400.jpg",
        description: "Bold and rich dark roast for true coffee connoisseurs."
    },
    {
        id: 13,
        name: "OKAZU Gift Set (4 jars)",
        category: "Chili oil:Okazu",
        type: "Multi Set",
        flavor: "Original",
        price: 75.00,
        oldPrice: 85.00,
        rating: 5,
        reviews: 26,
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL5CffeMXo6YG6Oobq1jx3njhnVkg7labHLA&s",
        description: "Perfect gift set featuring our best-selling OKAZU varieties."
    },
    {
        id: 14,
        name: "Traditional Miso Soup (Single Pack)",
        category: "Miso Soup",
        type: "Single Pack",
        flavor: "Original",
        price: 8.99,
        oldPrice: null,
        rating: 4.2,
        reviews: 9,
        image: "https://www.abokichi.com/cdn/shop/products/20220929_Original.png?v=1668571633",
        description: "Classic miso soup made with traditional fermentation methods."
    },
    {
        id: 15,
        name: "Matcha Latte Mix",
        category: "Instant Matcha",
        type: "Single Pack",
        flavor: "Original",
        price: 22.00,
        oldPrice: null,
        rating: 4.7,
        reviews: 15,
        image: "https://www.worldmarket.com/dw/image/v2/BJWT_PRD/on/demandware.static/-/Sites-wm-master-catalog/default/dwfbedeb08/images/large/128151_XXX_v1.jpg?sw=768&sh=768&sm=fit&sfrm=jpg&q=80",
        description: "Convenient matcha latte mix for quick and delicious drinks."
    },
    {
        id: 16,
        name: "Coffee Sampler Pack",
        category: "Coffee",
        type: "Multi Set",
        flavor: "Original",
        price: 29.99,
        oldPrice: 35.00,
        rating: 4.5,
        reviews: 13,
        image:"https://images-cdn.ubuy.co.in/63d00e8528369c597269ef22-sampler-coffee-variety-pack-100.jpg",
        description: "Try all our coffee blends with this comprehensive sampler pack."
    },
    {
        id: 17,
        name: "OKAZU Limited Edition",
        category: "Chili oil:Okazu",
        type: "Single Pack",
        flavor: "Spicy",
        price: 16.99,
        oldPrice: null,
        rating: 5,
        reviews: 31,
        image: "https://www.abokichi.com/cdn/shop/files/1_786849a4-c0e6-461a-8c2b-6428fdbd4cb5.png?v=1757592207&width=480",
        description: "Special limited edition flavor available for a short time only!"
    },
    {
        id: 18,
        name: "Miso Soup Premium Bundle",
        category: "Miso Soup",
        type: "Multi Set",
        flavor: "Original",
        price: 42.00,
        oldPrice: 50.00,
        rating: 4.8,
        reviews: 19,
        image: "https://www.abokichi.com/cdn/shop/products/BulkMisoSpicy.png?v=1672427493&width=480",
        description: "Our most comprehensive miso soup bundle with 12 servings."
    }
];
